# Generated by Django 6.0 on 2025-12-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatHistory',
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='bot_reply',
            new_name='ai_reply',
        ),
    ]
